:linkattrs:
:urlGeneralAct: assets/files/<general_act>.pdf
:urlHowTo: en/wizard

= GENERAL TERMS AND PRIVACY POLICY FOR THE USE OF THE Open Nettest SYSTEM FOR MEASURING THE QUALITY OF BROADBAND SERVICE

== General Terms for the use of the Open Nettest system for measuring the quality of broadband service

<organization> offers users the opportunity to use the Open Nettest software to test the quality and capacity of their current broadband connection. Children under 15 can use the Open Nettest with parental consent or consent of their legal guardian.

Using Open Nettest on mobile devices may cause consumption of large data amount. By using it on 3G technology the usual data amount would be between 5 and 10 MB. On 4G data amount may exceed 100 MB. Both assumptions are done using quality service. Agency takes no responsibility for large data consumption done by user and therefore related costs.

Open Nettest provides users with transparent and detailed information on the current quality of their broadband access service while respecting their privacy. The test is based on the open source and open data principle. Open source principle means that the source code of Open Nettest software is published completely. This is mainly for transparency and reliability issues. Any commercial use of Open Nettest source code, which is published under the MAME license, is not allowed. The Open Nettest logo and font are not subject to the open source and open data principle and copying, modifying or processing them in changed or unchanged form is strictly prohibited. Open Nettest measurement results data are retrievable as Open Data and available for re-use under the https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 (CC BY 4.0)], so they are freely available to the general public for information, use, dissemination and other applications. Data which are not retrievable as Open Data are not subject to the open data principle.

Links and references to other websites or persons outside the Agency are provided to facilitate use and should not be deemed as approved by the Agency. The Agency offers the service only to provide a greater and easier public access to information. Where the website ( example.org) includes links to other websites, the Agency shall not be deemed responsible for their content, copyright or privacy policy, and shall not be held liable for any damage which the user incur due or in connection to the use of the website, or use of any resources or services offered by the relevant website, even if the Agency has been informed on the possibility for such damage or should reasonably anticipate such loss or damage.

The Agency shall try to regularly update the browser and app version of the Open Nettest, but it does not provide any warranties for the permanent availability of the Open Nettest and explicitly reserves the right to change, add to or delete parts of the Open Nettest or the entire Open Nettest without prior announcement, or to cease publication of it temporarily or finally.

Open Nettest is an agency-certified measurement and analytics tool that allows end users of Internet access services to perform measurements of Internet connection performance, quality and transparency. The measurement resulting from the use of the Open Nettest measurement tool and performed in accordance with the link:{urlGeneralAct}["*General Act on Internet Access Services and Related End User Rights (Article 11)*", window="_self"] is the basis for the user's reporting a fault to his service provider and as such, taking into account all relevant circumstances, may indicate a failure or impairment of the services.

Measurement instructions are available link:{urlHowTo}[*here*].

Measurements that are NOT performed in accordance with the link:{urlGeneralAct}[*General Act on Internet Access Services and Related End User Rights (Article 11)*, window="_self"] are, due to the number of factors that may affect them, for informational purposes only!

The Agency accepts no responsibility for the up-to-dateness, correctness, completeness, or quality of the published open data. In order to ensure the correctness of the results, the Agency may mark and / or exclude measurements that have proven to be incorrect. The Agency shall not be liable for any material or non-pecuniary damage to operators, users or anyone else arising from the use or misuse of data or from the use of incorrect or incomplete data. When the Agency cannot waive liability for incurred damage in accordance with the law applicable in a specific case, its liability shall be limited to negligence and intent.

== Privacy policy
The Agency respects the right to privacy, so it carefully protects personal data. The processing of personal data obtained by the agency using the Open Nettest software is processed by the agency in accordance with European legislation (Regulation (EU) 2016/697 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (hereinafter: General Data Protection Regulation) and applicable legislation in the field of personal data protection (Personal Data Protection Act; ZVOP-1) and other legislation that provides the agency with a legal basis for the processing of personal data. Specifically, pursuant to Article 6 (1) (b) of the General Data Protection Regulation, the agency processes the personal data collected (i.e. platform, browser type, public IP address (anonymized) and geographic location of the executed measurement) for the purpose of providing the current broadband connections.

*Use of Open Nettest requires confirmation from the user that he is aware of and agrees to the Terms of Use and Privacy Policy.* pass:[<u>By confirming the Terms of Use and Privacy Policy, the user agrees to the manner and conditions under which the agency (as the personal data controller) collects and processes their personal data specified under section 2.1.1 for the purposes specified under section 2.1.2.</u>] Confirmation (YES / NO) is logged for evidential purposes of recording that the Terms of Use and Privacy Policy were accepted and that the user has approached the use of the Open Nettest measurement system. When changes are made to the processing and transmission of data (in connection with updates or new releases of the Open Nettest), users will have to renew their acceptance of the General Terms of Use and Privacy Policy.

The Agency shall collect, keep and process users' personal data pursuant to provisions of the General Data Protection Regulation and ZVOP-1, as well as the agency's internal acts. Personal data are not collected for commercial purposes in any way. The Agency shall not try to identify specific users, nor shall it link the collected data therewith, except with the consent of the users.

For any questions regarding personal data protection and privacy policy when using the Open Nettest system for measuring the quality of broadband service or regarding the exercise of individual rights regarding data processing, please contact the personal data controller: Agency for Communication Networks and Services of the Republic of Slovenia, e-mail address example@example.org or to the data protection officer: example@example.org.

Using Open Nettest, the agency processes the data listed under point 2.1.1. These data also include personal data, namely: 

- public IP address of the user, 
- geographic location of the measurement.

=== Open Nettest

==== What data are processed and transmitted?

In the browser version of the Open Nettest the following data are processed:

* Ping (latency), speed and quantity of transmitted data in both directions (downlink/uplink); *
* Quality and transparency parameters (e.g. signal strength, connectivity on different ports, modifications of content, transfer time for a reference web page), and reliability of the measurement; *
* Test parameters (test method, test progress, test server, test configuration (e.g. test duration));*
* Randomly generated client ID (client UUID) and the number of performed tests;
* Public client ID (changed every 24h);*
* Client sync code and information on the client (language, local IP, version, test time and time band);*
* Indicator of the network address translation mechanisms (NAT/PAT);*
* IP version used (IPv4 or IPv6);*
* Public IP address of the user;
* WLAN network ID (WiFi SSID), numerical WLAN ID (WiFi BSSID) and encryption type;
* Name and country of service provider;*
* Geographic location of the client and direction of movement;+
* Type of device/model, OS/Open Nettest app version;+
* Public measurement ID (generated upon each measurement);+
* Anonymized public IP address (hidden last octet).

Data not marked with ( * ) *are not transmitted (public)* and *shall not be disclosed*. This data shall be accessed by the Agency only.

The data marked with asterisk ( * ) *are transmitted*; i.e. *published* and *visible* to everyone through the Open Nettest, and *made freely available* to the general public as Open Data for information, use and dissemination.

The data marked with plus sign ( + ) *are published* and *visible* to everyone on the Open Nettest website and can be freely accessed as open data for information, use and dissemination only *upon explicit approval of the user*.

Users can at any time withdraw their acceptance of publication of the above specified data by deleting the "opendata" cookie in the "Settings" menu of their browser. Withdrawal of acceptance acts for future activities and it does not mean deleting old data stored. In the event that after the first completed measurement the user does not approve the publication of data on the client’s geolocation and direction of movement, type or model of device, OS and version of the Open Nettest app used, public measurement ID generated upon each measurement, and anonymized public IP address, the above-specified data shall not be published on the website. However, they shall remain visible in the history of the completed tests, which can be accessed by the user, and recorded in the Open Nettest database managed by the Agency. The only exception is the geographic location of the user, which is (in the event of absence of the user’s approval for publication) anonymized to the circle of 300m and published in this form.

The browser version of the Open Nettest uses cookies. Cookies are small text files which are loaded in the client with the aim to improve the user experience. Open Nettest uses four cookies, which are required for the operation of the test: 

* name: RBMTTermsV2; purpose: stores the information on the user’s acceptance of the Terms of Use and Privacy Policy; stored for: 10 years.
* name: RMBTuuid; purpose: stores ID of the client (client UUID); stored for: 1 year.
* name : coord; purpose: stores the user’s location in the event that such information exists; Stored for: 1 hour.
* name : opendata; purpose: stores the information on the user’s acceptance of publication of information, marked with plus sign (+); stored for: 10 years.

*pass:[<u>By accepting the Terms of Use and Privacy Policy the user also grants explicit approval for the use an storage of cookies.</u>]*

Users can withdraw their acceptance of publication of the above specified data at any time by deleting all cookies related to the example.org website in the "Options" menu of their respective browsers. After this the user will no longer be able to use the Open Nettest without re-accepting the Terms of Use and Privacy Policy which inform the user on the use of cookies.

==== The purpose of personal data collection

===== Primary database
All data acquired by the Agency acquired through the use of Open Nettest and results of all measurements (all data listed under section 2.1.1), which are carried out by users or the Agency are recorded in the primary database. The primary database can only be accessed by the employees of the Agency responsible for the management of the database. Users and the Agency shall use the Open Nettest system to measure the capacity and quality of network services provided by operators or service providers. The Agency shall use the collected data in order to monitor the situation and to carry out regulatory supervision in the field of fixed or mobile broadband services. The system shall show the Agency where in Slovenia and with which ISPs there are potential problems with access to internet services, where there is no mobile or wireless signal and whether operators are expanding the coverage of the specified white spots with mobile and wireless access pursuant to decisions on the assignment of radio frequencies.

All data listed under section 2.1.1 are kept in the primary database for a period of 10 years, with the exception of the user’s public IP address, which is kept for a period of 6 months.

The user’s public IP address is being processed in order to determine the network operator, to identify potential improper use of the system and in order to prepare a history of measurements for a specific user. After the completed test the only the network address of the IP address (anonymized public IP address) is recorded in the database and can be accessed in accordance with the open data principle. The full IP address is recorded in the primary database, but shall not be disclosed to public and can be viewed by the user only in the mobile app under "Details" or in the browser under the "History" tab.
Data on WLAN network ID is stored for the purposes of interpreting his own results of users by having overlook on this information to all his measurements stored. This is critical especially when different WiFi access points are used.

===== Public database
The selected and anonymised data from completed measurements (marked with one asterisk ( * ) or plus sign ( + ), when the user explicitly allows it) are published online and can be accessed through the example.org website, while allowing the interested public to gain an independent and realistic insight in the state of mobile, wireless and fixed communication systems and internet services on the territory of Slovenia. They provide users with information on the network coverage for a specific network or service provider at the level of regions, cities, districts or the most common regular communication routes. Information on mobile coverage is especially important for users, who travel on Slovenian territory on a daily basis, or users without the possibilities to access fixed broadband networks.

The data stored in the public database are kept for a period of 10 years.

===== Protection of personal data
The agency takes care of information security and security of premises and application system software. Accordingly, the agency has taken appropriate organizational and technical security measures to protect the personal data of individuals against accidental or unlawful destruction, loss, alteration, unauthorized disclosure or access, and other illegal and unauthorized forms of processing. Information systems are protected by anti-virus programs and a firewall. The data are not exported to third countries and are not passed on to unauthorized third parties. After the retention period, the agency anonymizes personal data so that it can no longer be linked to a specific individual.

===== Individual rights regarding data processing
In accordance with the General Data Protection Regulation, the individual has the following, in particular from the protection of personal data, rights: 

* the right to obtain from the agency confirmation as to whether personal data concerning him are being processed,
* the right to access to the personal data, which allows him to receive a copy of the personal data held by the agency about him and to verify that he is processing them lawfully,
* the right to request the rectification of personal data concerning him, 
* the right to object to the further processing of their personal data, 
* the right to erasure of personal data concerning him when there is no reason for further processing or when he exercises his right to object to the further processing, 
* the right to restriction of processing of his personal data or an interruption of the processing of personal data on him, 
* the right to data portability in a structured machine-readable format and have the right to transmit those data to another controller.

If a user wishes to exercise any of the aforementioned rights, he sends a request by e-mail to example@example.org or by regular mail to the agency's address: Agency for Communication Networks and Services of the Republic of Slovenia, Stegne 7, 1000 Ljubljanafootnote:[In the case of exercising the rights under this title, the agency is expected to request certain information from the individual to confirm his identity, which is only a security measure to ensure greater security of personal data, especially not to disclose them to unauthorized persons.]. 

Exceptionally, the agency may reject a request to erasure on the grounds set out in the General Data Protection Regulation. These reasons are: exercising the right to freedom of expression and information, for compliance with a legal obligation, for reasons of public interest in the area of public health, for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes or for the establishment, exercise or defence of legal claims.

Access to personal data of an individual and the exercise of rights in relation to personal data is provided free of charge. However, the agency reserves the right to charge a reasonable fee if the request of the data subject are manifestly unfounded or excessive, in particular if repeated. In such a case, the agency may also refuse to act on the request.

Protection and assistance in the event of a violation of an individual's rights in relation to the protection of personal data is provided by the Information Commissioner of the Republic of Slovenia. The link for more information regarding reporting security breaches is: https://www.ip-rs.si/zakonodaja/reforma-evropskega-zakonodajnega-okvira-za-varstvo-osebnih-podatkov/kljucna-podrocja-uredbe/prijava-krsitev/.

On the page of the Information Commissioner of the Republic of Slovenia there is also a form for acquaintance with one's own personal data (which is only for help, it is not prescribed): https://www.ip-rs.si/fileadmin/user_upload/doc/obrazci/ZVOP/Zahteva_za_seznanitev_z_lastnimi_osebnimi_podatki__Obrazec_SLOP_.doc.

