= GENERAL TERMS FOR THE USE OF THE Open Nettest SYSTEM FOR MEASURING THE QUALITY OF BROADBAND SERVICE

<organization> offers users the    opportunity to use the Open Nettest software to test the quality and capacity of their current broadband connection. Children under 15 can use the Open Nettest with parental consent or consent of their legal guardian. 

Using Open Nettest on mobile devices may cause consumption of large data amount. By using it on 3G technology the usual data amount would be between 5 and    10 MB. On 4G data amount may exceed *100 MB*. Both assumptions are done using quality service. Agency takes no responsibility for large data consumption done    by user and therefore related costs. 

Open Nettest provides users with transparent and detailed information on the current quality of their broadband access service while respecting their privacy. The test is based on the open source and open data principle. Open source principle means that the source code of Open Nettest software is published completely. This is mainly for transparency and reliability issues. Any commercial use of Open Nettest source code, which is published under the MAME license, is not allowed. The Open Nettest logo and font are not subject to the open source and open data principle and copying, modifying or processing them in changed or unchanged form is strictly prohibited. Open Nettest measurement results data are retrievable as https://example.org/en/opendata[Open Data] and available for re-use under the  https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 (CC BY 4.0)], so they are freely available to the general public for information, use, dissemination and other applications. Data which are not retrievable as Open Data are not subject to the open data principle. 

Links and references to other websites or persons outside the Agency are provided to facilitate use and should not be deemed as approved by the Agency. The Agency offers the service only to provide a greater and easier public access to information. Where the website (https://example.org/[example.org]) includes links to other websites, the Agency shall not be deemed responsible for their content, copyright or privacy policy, and shall not be held liable for any damage which the user incur due or in connection to the use of the website, or use of any resources or services offered by the relevant website, even if the Agency has been informed on the possibility for such damage or should reasonably    anticipate such loss or damage. 

The Agency shall try to regularly update the browser and app version of the Open Nettest, but it does not provide any warranties for the permanent    availability of the Open Nettest and explicitly reserves the right to change, add to or delete parts of the Open Nettest or the entire Open Nettest    without prior announcement, or to cease publication of it temporarily or finally. 

The measurement resulting from the use of the Open Nettest measurement tool and performed in accordance with the General Act on Internet Access Services and Related End User Rights (Article 11) is the basis for the user’s reporting a fault to his service provider and as such, taking into account all relevant circumstances, may indicate a failure or impairment of the services.
Measurements that are NOT performed in accordance with the General Act on Internet Access Services and Related End User Rights (Article 11) are, due to the number of factors that may affect them, for informational purposes only!

The Agency accepts no responsibility for the up-to-dateness, correctness, completeness, or quality of the published open data. In order to ensure the correctness of the results, the Agency may mark and / or exclude measurements that have proven to be incorrect. The Agency shall not be liable for any material or non-pecuniary damage to operators, users or anyone else arising from the use or misuse of data or from the use of incorrect or incomplete data. When the Agency cannot waive liability for incurred damage in accordance with the law applicable in a specific case, its liability shall be limited to negligence and intent.



